### ISSUE TITLE
Operator with dot .= 

### ISSUE THREAD

**Issue by moeinkh88** [JuliaTurkuDataScience/FdeSolver.jl#14]
You used .= in some parts of the main code. For example,  in line 24 we have: Y[2, :] .= T0 .+ h .^ β .* F(t, n, β, Y, par...) ./ Γ(β .+ 1)

 I found it problematic in some cases, e.g. for the solution of Gonze model with N species.

So, I replaced = instead of .= from the main.jl.

If you think the presence of .= is so crucial, let me know to think more about it. If not, let's remove dots.

**Comment by moeinkh88** [comment]
OK. It seems it is important. I will work on it.

**Comment by RiboRings** [comment]
Hey! The component-wise .= makes the 1FDE case work. Without the dot, I used to get an error of dimensionality.

**Comment by moeinkh88** [comment]
> Hey! The component-wise .= makes the 1FDE case work. Without the dot, I used to get an error of dimensionality.

Yes. I see :)
