### ISSUE TITLE
Minor Error in Example 1

### ISSUE THREAD

**Issue by mapi1** [JuliaTurkuDataScience/FdeSolver.jl#37]
Just wanted to let you know there is a minor error in the first example of the Readme. Running it now gives:

`
ERROR: LoadError: MethodError: no method matching F(::Float64, ::Vector{Float64})
Closest candidates are:
  F(::Any, ::Any, ::Any) at ...`

As `par` seems to be missing from the `FDEsolver`  call. 

Otherwise, it was much fun to play around with the package, great work!

**Comment by moeinkh88** [comment]
> Just wanted to let you know there is a minor error in the first example of the Readme. Running it now gives:
> 
> ` ERROR: LoadError: MethodError: no method matching F(::Float64, ::Vector{Float64}) Closest candidates are: F(::Any, ::Any, ::Any) at ...`
> 
> As `par` seems to be missing from the `FDEsolver` call.
> 
> Otherwise, it was much fun to play around with the package, great work!

Thanks for informing me! 

True. It seems the Pkg wasn't updated properly. The local one works well, however. 

We will polish it soon and inform you here.

**Comment by RiboRings** [comment]
Hi! 

Thanks a lot for spotting that error. 💯
 
Nice that you found the package useful. 👍
